// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "myImage0":return img`
........................
........................
........................
........................
.........fffff..........
........f11111ff........
.......fb111111bf.......
.......f1111111dbf......
......fd111111dddf......
......fd11111ddddf......
......fd11dddddddf......
......f111dddddddf......
......f11fcddddddf......
.....fb1111bdddbf.......
.....f1b1bdfcfff........
.....fbfbffffffff.......
......fffffffffff.ff....
...........ffffffff.....
........f1b1bffffff.....
........fbfbffffff......
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
